version: "3.9"
services:

  pgadmin:
    depends_on:
      - pytrader-db
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_CONFIG_SERVER_MODE
    image: dpage/pgadmin4
    networks:
      pytrader:
    ports:
      - "5050:80"
    volumes:
      - ./src/pytrader-pgadmin:/root/.pgadmin

  pytrader-db:
    build: ./src/pytrader-db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
    networks:
      pytrader:
    ports:
      - "5432:5432"
    volumes:
      - ./src/pytrader-db/.data:${PGDATA}
      - ./src/pytrader-db/src/init.sql:/docker-entrypoint-initdb.d/init.sql

  pytrader-redis:
    build: ./src/pytrader-redis
    command: redis-server --requirepass $REDIS_PASSWORD
    environment:
      - REDIS_PASSWORD
    networks:
      pytrader:
    ports:
      - "6379:6379"
    volumes:
      - ./src/pytrader-redis/.data:/redis-master-data

networks:
  pytrader:
    name: pytrader
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
